// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "adder": swagger TestHelpers
//
// Command:
// $ goagen
// --design=goa-adder/design
// --out=$(GOPATH)/src/goa-adder/generate
// --version=v1.3.0

package test
